### ISSUE TITLE
Clarify whether apps are expected to have their own subdomain

### ISSUE THREAD

**Issue by untitaker** [remotestorage/spec#104]
Currently 5apps' app launcher makes that assumption.

**Comment by skddc** [comment]
I'm not sure I understand this one. Are you referring apps being tied to an origin?

**Comment by untitaker** [comment]
Yes. As far as I understand it's not allowed to host apps on subpaths?

**Comment by michielbdejong** [comment]
Each app should have their own origin, but is free to use URL paths within that for navigation through the app's views. What exactly is the 'root path'? I think the launch path for storage-first flow should usually be the same as the `redirect_uri` used in OAuth?

**Comment by untitaker** [comment]
If each app has their own origin, the root path of each app would be /.

5apps' launcher replaces the path component of `redirect_uri` with `/` when launching apps.

**Comment by fkooman** [comment]
The 'storage first' should never send the browser to the redirect_uri, but to the 'index.html' or 'root URL' and also never directly embed the access_token. I saw this somehow sneaked into the spec, which is then later also warned against (CSRF) and also in the process gets rid of the state parameter, because obviously that wouldn't work...

My storage first server all those years ago worked without passing access_token, worked _with_ state parameter and had the same UX as this 'shortcut'.

The current widget does not display clearly the storage server that is connected to. Only when clicking the RS icon.

**Comment by untitaker** [comment]
>**Each app should have their own origin**, but is free to use URL paths within that for navigation through the app's views.

@michielbdejong To clarify, this already completely answers my question. I want this to be clarified in the spec, because I used to host an app of mine on the same host as a few other things (to spare SSL configuration hassle).

**Comment by untitaker** [comment]
@skddc said in IRC that the web as a whole already assumes each "app" to have their own origin, but IMO this is not explicit enough.

Usually the origin isn't visible to the user, so it's reasonable for developers to put many things on the same origin if they already share a server.

In RS, you get usability issues when many apps share an origin and are represented as one app in the server's web interface.

**Comment by michielbdejong** [comment]
@untitaker It's clarified by https://github.com/remotestorage/spec/pull/110/files

**Comment by untitaker** [comment]
I think this can be closed, even though the MAY seems kind of weak to me.
