### ISSUE TITLE
Changes in draft-dejong-remotestorage-06 but not in source.txt

### ISSUE THREAD

**Issue by untitaker** [remotestorage/spec#129]
@michielbdejong You accidentally pushed #127 to master.

**Comment by untitaker** [comment]
argh nvm I get it

**Comment by untitaker** [comment]
No, actually there's still a problem. You changed `draft-dejong-remotestorage-06`, but not `source`.

**Comment by michielbdejong** [comment]
Difference between source.txt and the built release file fixed with https://github.com/remotestorage/spec/commit/9e14a6e87a1209f85958421cb984348e5c5731e0, right?

I also moved the built release files to a `release/` folder, to make it less confusing in the future.

> you merged those broken commits untouched to master.

AFAICS, no commits were accidentally merged from https://github.com/remotestorage/spec/pull/127 but please open an issue if there were any, so we can fix that for the 07 spec. I just checked the top one, da00a4a, and that one is unmerged (instead I opened #135 about that).

**Comment by untitaker** [comment]
LGTM

On 1 December 2015 09:02:06 CET, Michiel de Jong <notifications@github.com> wrote:
>Difference between source.txt and the built release file fixed with
>https://github.com/remotestorage/spec/commit/9e14a6e87a1209f85958421cb984348e5c5731e0,
>right?
>
>I also moved the built release files to a `release/` folder, to make it
>less confusing in the future.
>
>> you merged those broken commits untouched to master.
>
>AFAICS, no commits were accidentally merged from
>https://github.com/remotestorage/spec/pull/127 but please open an issue
>if there were any, so we can fix that for the 07 spec. I just checked
>the top one, da00a4a, and that one is unmerged (instead I opened #135
>about that).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/remotestorage/spec/issues/129#issuecomment-160888506

-- 
Sent from my phone. Please excuse my brevity.
