### ISSUE TITLE
Require Last-Modified dates

### ISSUE THREAD

**Issue by skddc** [remotestorage/spec#158]
In recent conversations on IRC, there was a desire from multiple people to have [Last-Modified](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) dates in folder listings and perhaps headers in GET and HEAD responses as well.

When we introduced ETags, we made thjose obsolete, but I think it would be useful for app developers to re-add the requirement.

**Comment by untitaker** [comment]
I think this is also an opportunity to discuss if we generally want to include all metadata the server knows about files (filesize) in the storage listing.

**Comment by skddc** [comment]
We do already include size via Content-Length. What other properties would be missing?

**Comment by untitaker** [comment]
Ah yes, I forgot that we already have that in the folder listing.

**Comment by gregkare** [comment]
I also think `Last-Modified` would be useful in both folder listings and headers. It's a fallback to an `ETag`, but it's much more human readable

**Comment by galfert** [comment]
Yes, I think it's useful , too.

I can't remember if there was any specific reasoning to completely remove it back then, instead of just keeping it in addition to the ETag.

**Comment by michielbdejong** [comment]
this would only be useful for developers, not for end-users, right? an end-user of for instance a todo-list app would see data like last-modified on the todo-items, not on the actual files. For instance, when you view this comment on github, you are an end-user of github, and you see e.g. '4 hours ago' on the comment display box, but you don't see the underlying database entry in github's backend. As a developer though, you do want to have direct access to the files on remoteStorage, and all handy information you can get.

if that's the case, i would propose making it a MAY, and probably also mentioning that this would be useful for debugging (not meant for end-users of apps to nose around in), right?

**Comment by skddc** [comment]
I think this is actually useful for end users, too. I opened this issue because I needed to know when my document changed as an end user, not as a developer. The person recently asking about it on IRC also asked because he needed to show his users without keeping a seperate index of when documents were edited.

**Comment by michielbdejong** [comment]
hm, it doesn't feel very clean to add this, but i can't really explain why.

**Comment by skddc** [comment]
Only `Last-Modified` as per HTTP spec.

We can also make it a SHOULD, but then developers have to deal with servers that don't support it, and the UX can be broken for some apps, depending on if the server author chose to support it. Thus, I think this should be a MUST. ;)

About it being clean: this is as standard HTTP as it gets, and is supposed to be added "whenever feasible" anyway. I don't see what would be dirty about it.

**Comment by michielbdejong** [comment]
> is supposed to be added "whenever feasible" anyway

 is that what the http spec says, even when E-Tag headers can already be used for caching?

If the server sends `Last-Modified`, should it then also handle `If-Modified-Since`/`If-Not-Modified-Since`? I guess what I find dirty about it is that doing one but not the other, it seems like we would be adding this header for informational purposes, and not for versioning purposes.

Also, having it in parallel to the E-Tag <-> If-Match/If-None-Match system feels like a duplication; for instance, what if the `Last-Modified` header changed but the `E-Tag` did not, would that be a allowed or a bug?

**Comment by skddc** [comment]
> is that what the http spec says, even when E-Tag headers can already be used for caching?

Yes, that's exactly what it says: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

> If the server sends Last-Modified, should it then also handle If-Modified-Since/If-Not-Modified-Since? I guess what I find dirty about it is that doing one but not the other, it seems like we would be adding this header for informational purposes, and not for versioning purposes.

Ah, I see. This is a good question, that I don't have an opinion on yet. At first sight, I don't see why it would have to support versioning, and cannot just be an informational header. There's nothing in HTTP that requires both at once.

> Also, having it in parallel to the E-Tag <-> If-Match/If-None-Match system feels like a duplication; for instance, what if the Last-Modified header changed but the E-Tag did not, would that be allowed or a bug?

It's not duplication if only ETag is used for versioning. The situation you describe would be extremely unlikely, as "modified" means the content should have changed, which would result in a new ETag as well.

**Comment by michielbdejong** [comment]
If we add it as optional, then developers have to deal with servers that don't support it, depending on if the server author chose to implement it, otherwise their UX will be broken.

I think the brokenness will be quite manageable - in the place where the app would usually display the Last-Modified date (translated to the user's timezone, probably?), just either display nothing (if it was just additional info in a listing), or display "unknown" if the user explicitly asked about the Last-Modified date.

Previously, I wanted all servers to behave in the same way, but now I think there will always be differences in for instance max upload size, so as long as we have clear ways to deal with the difference (e.g. a clear error response in the http status code), it might be ok if behaviors differ. And then, I think this is an example where a feature being optional is maybe easier than that feature being required from all servers? it would be a disaster if two servers use a different encoding or header name for the same thing, and the client would have to guess which one to use this time- but if the header is missing, it's pretty obvious that this particular server does not send it.

**Comment by skddc** [comment]
I understand where you're coming from, but you didn't actually bring forward a good argument against requiring this particular header. There's really not much complexity added, and you operate on the assumptions that it's a totally optional thing in most cases. Which is true for some apps, but not true for many of the use cases we talked about, and for which I opened this issue.

For example showing documents in a folder sorted by recent changes, and only showing x recent ones, is an integral part of the UI of many apps and cannot be made optional usually. You cannot just optionally show random documents or recent ones.

**Comment by skddc** [comment]
> but i would like to keep the option open that some servers will not send this header, since they're already sending E-Tag

In RS app development, we do not need this header for versioning at all, and the ETag is utterly irrelevant for knowing what's a recent document and what is not. This request has nothing to do with anything that can already be solved by using ETag. Otherwise people would just do that.

**Comment by skddc** [comment]
Update: I checked how much work it would be to add it to 5apps Storage, and was able to implement it rather quickly. Mostly due to the fact that we already store that date in our metadata, but it wouldn't be much more work to add it to the places where our code already has it:

https://github.com/5apps/liquor-cabinet/commit/bc957bf2efb8b090dcdf2c34eda02208cb5809a5

**Comment by skddc** [comment]
Update: So far, I couldn't find any clients/apps being affected negatively by this change. I tried both caching and non-caching rs.js apps, as well as my custom backup/restore client.

**Comment by michielbdejong** [comment]
I think it would be ok to add Last-Modified as a required informational field in folder listings, if that's what the current active community wants.

On GET responses I would keep it optional (i guess it's already currently optional), because if it's required, that would be too confusing next to the ETag.

**Comment by michielbdejong** [comment]
if you want to have this in version 11, which will be published on Thursday, then please open a PR for it.
