### ISSUE TITLE
Consider adding Kinto's extra features as extensions

### ISSUE THREAD

**Issue by michielbdejong** [remotestorage/spec#90]
[Kinto's API](http://cliquet.readthedocs.org/en/latest/api/index.html) adds a few features compared to remoteStorage-05:
* paging, filtering, and count on folder listings
* setting permissions per folder
* PATCH verb
* batch operations

If we define these as optional features a server can announce, then our spec would describe what Kinto does in practice, so that an app developer can use a remoteStorage client to store data on a Kinto server, which effectively gives the remoteStorage spec a brighter future.

CC @fkooman

**Comment by skddc** [comment]
Wow, that's *a lot* of extra features. Seeing that even something like a HEAD request was almost impossible to get into the spec in the past (not even talking about the famous battle of content types in dir listings of 2013), may I ask what changed your opinion on spec/server complexity and what led you to consider quadrupling it?

**Comment by fkooman** [comment]
My bad :P 

We talked a little bit about the specification today and associated discovery mechanisms in the specification. It seems the only added feature of RS over other storage protocols (Google, Dropbox, ...) is the discovery to make it "decentralized". And even the discovery has always been something that didn't feel quite right (at least to me). One should (directly) specify the storage server and not a 'user address'. Combining this with OAuth AS discovery as for example like in my blog post on the subject [1] make the specification a lot less useful. The whole world uses Google or Dropbox and for the IndieWeb...well... why not use something that exists, inspired by remoteStorage, as a base for the "Indie" version of remoteStorage. The library supports (or will support?) Google Drive, Dropbox, current RS, and why not also Mozilla's horse in the race.

Personally, I don't really see much use for the RS spec as is anymore. I think it makes more sense to split it up in two parts: describing the use of OAuth, some form of discovery of the AS, CORS and the minimal requirements for such a storage system in one document and the actual REST protocol for storing the data in a separate one. At that point it probably makes sense to drop the "RS storage protocol" and use something with more community backing, or even something as legacy as WebDAV :-)

[1] https://www.tuxed.net/fkooman/blog/as_discovery.html

**Comment by skddc** [comment]
I disagree about the discovery (at least about dropping it from the spec in favor of URLs, which has failed miserably for e.g. OpenID), as in the wild this has been the strong point of remoteStorage during the last few years. I think we could probably improve the experience by making the user@ bit optional, though.

In any case, I think this discussion should be had, except I don't see how supporting other backends in the reference client library has anything to do with changing the RS protocol in this way.

I'm not opposed to these additions in general, but after what we went through trying to get tiny features added to the spec in the past, I think everybody deserves to learn what inspired this 180-degree turn first, and that all current implementors and users need to take part in this discussion, because it has huge implications for all sides. If added to the RS spec, it would basically mean RS going from Webfinger+OAuth+REST to Webfinger+OAuth+Kinto, meaning people have to rewrite all existing software, both server and client (which is not a bad thing for clients I think and could be OK for servers, too).

As the feature list seems too big to easily create a new server, it also means potentially being dependent on a single implementation by Mozilla, having the whole thing misused with FF Accounts only, and then dying due to the actual spec and discovery being embraced and extinguished by a corporate entity.

So, @michielbdejong, maybe you can shed some light on your opinion change and especially the implications, roadmap etc. regarding Mozilla and FXOS Sync in this story?

**Comment by michielbdejong** [comment]
I didn't mean adding this features to the list of things every remoteStorage should be able to do, I agree it's way too much for even considering that. But we could just add ways to announce these as extra features, like https://github.com/remotestorage/spec/blob/master/draft-dejong-remotestorage-05.txt#L520 and https://github.com/remotestorage/spec/blob/master/draft-dejong-remotestorage-05.txt#L528.

**Comment by skddc** [comment]
Thanks. I actually assumed that would be the case anyway. All questions remain the same.

**Comment by untitaker** [comment]
Please don't add any of those features in any way, not even optional, and keep the spec minimal instead. Consider WebDAV, which has so many third-party extensions that make it impossible to write a server that accomodates all clients.

**Comment by fkooman** [comment]
@skddc but has user discovery not failed? It is, at least to me, confusing to use `fkooman@5apps.com` to use "my" remote storage. It is not my email address! So I guess it would only work better if it were my primary email address as well. But that also failed (Persona). Yeah making `user@` optional makes sense. I'd like to push for WebID/IndieCert though, ideally without requiring your own domain, but with email address verification or something... I still have to think about that.

So a rewrite of servers and clients is not a (big) problem? :-) So then then that is not really an issue. 

I think the point of a specification should not necessarily be that it is easy to write your own server, I mean, even writing a remoteStorage server is *HARD*. To do it correctly at least. There are many exceptions and issues when using "real" file system storage to get things working correctly, for example the updating ETag of parent folders when you change a file. Do you have an estimation how many hours it took you to implement RS for 5apps? Including writing test suites (both integration and unit) to be reasonably confident stuff doesn't break?

Using something like Kinto, or even WebDAV, and defining a profile of what servers need to at least support give you a lot of stuff for free: i.e. already tested and a big community of users. I mean, for me it would be great if I could using something like SabreDAV for PHP and just need to write Bearer token support and integrate with the ACL handling of DAV to get the permissions going.

Maybe I'm just getting old and lazy and am tired of reinventing the wheel all the time ;)

**Comment by skddc** [comment]
Just FYI: was without Internet on a mountain hut over the weekend and will take another day or two until I have time to address your comment.

Still missing @michielbdejong's answers, though. Especially because the original proposal here was not about using WebDAV instead of the current minimalistic subset of HTTP.

**Comment by skddc** [comment]
Also, maybe someone address @untitaker's comment:

> Please don't add any of those features in any way, not even optional, and keep the spec minimal instead. Consider WebDAV, which has so many third-party extensions that make it impossible to write a server that accomodates all clients.

He's currently implementing a client in Python to be used in a desktop app afaik.

**Comment by michielbdejong** [comment]
Yeah, maybe it's easier to just leave the remoteStorage spec as it is. It was just an idea that came up over coffee. :)
